//console.log("HELLO")
// Value and Datatype

//primitive data type
//numbe-1 2 34 
//String- "Anand"
//Boolean- true,false
//null
//undefinde

//non-primitive data type
//arry
// let arr=[1,2,3,4]
// console.log(arr)
//object- {}
//examle
// let pwPrice=200;
// let gst=34;
// let totalPrice=pwPrice+gst;
// console.log(totalPrice);
// let num1=222
// let num2="222"
// console.log(num1===num2);
let login=true;
let= cardDetails=false;
let result=login && cardDetails
//console.log(result)
if(result==false)
{
    console.log("PLZ Add CardDetails");
    
}






